### ISSUE TITLE
spec test fails to compile

### ISSUE THREAD

**Issue by mmarseglia** [echocat/puppet-redis#56]
I saw issue #36 and I have the same problem.  I looked at your spec test and I don't see $::path defined there.  How are your tests passing?

Also, isn't it best practice to use a File resource or ensure_resource were used instead of exec?

````
file { 'redis build directory' : 
  path => $redis_build_dir,
  ensure => 'directory',
}
````

or

````
ensure_resource('file', "${redis_build_dir}", { 'ensure' => 'present' })
````

**Comment by dwerder** [comment]
As I wrote in the issue you mentioned, the $::path variable is a global puppet variable. SO if you have puppet installed. It should exist. And travis-ci and my own workstation have no problems with the spec test and they are passing.

$::path should by default be the same as your global env path variable ( /bin:/usr/bin:/usr/local/bin etc) How is your puppet setup, that this variable is empty?
We can set something like 
```Exec { path => '/bin:/usr/bin:/usr/sbin' }```
if necessary.

And I think you mean the exec "Make dir ${redis_build_dir}"  at this point https://github.com/echocat/puppet-redis/blob/develop/manifests/install.pp#L76 ?

If so, the reason for the exec is, that ${redis_build_dir} can be something else then /opt. For example it can be /usr/local/myspace/myredis. The File resource would fail then. Because it would only try to create myredis with the error that myspace doesn't exist. File can't handle things similar to "mkdir -p"

I also don't get the point, why you are opening a new ticket, if you know that a ticket already exists.

**Comment by mmarseglia** [comment]
Thank you for taking the time to explain.  I am not sure why Travis passes while when I run "rake spec" on my manifest that includes redis fails.  I was wondering if you had to specify $::path somewhere for your test to pass.

I see your point about using a mkdir -p versus a file resource.  That's something I didn't consider.
